### ISSUE TITLE
don't allow reading .env files from the script

### ISSUE THREAD

**Issue by pelikhan** [microsoft/genaiscript#231]

**Comment by sinjup** [comment]
Why is this not supported? If we want to use a specific model, how can we achieve it without hardcoding?

**Comment by pelikhan** [comment]
This was a basic feature to prevent "trivially" leaking secrets to the LLMs.

You do have access to process.env where the .env most likely has been imported. Otherwise, you can user fs.readFile.

Up for discussion.
