### ISSUE TITLE
New users will often run the GenAIScript on the GenAIScript file itself, causing confusion

### ISSUE THREAD

**Issue by bzorn** [microsoft/genaiscript#267]
It isn't obvious that you should select another file to operate on from the file explorer and so users will just right click on the current file (the script) and run the GenAIScript on itself, causing confusing results.  We should highlight that the right click should be on another file. Alternately, we should illustrate scenarios where the script doesn't need any file as input and it just runs without any context, which is also a chat-like experience.

**Comment by pelikhan** [comment]
vscode now handles running .genai.js as a starter. It will run without a context.
