### ISSUE TITLE
Handle accidently empty context more gracefully

### ISSUE THREAD

**Issue by bzorn** [microsoft/genaiscript#268]
When the user incorrectly specifies the input context (via a typo or misunderstanding), the LLM sees an empty input but still tries to do the task, which can cause hallucinations and confusion.  Maybe we should support turning on warnings or suggesting users look at the trace to understand what happens in these cases.

**Comment by pelikhan** [comment]
Do we want to throw by default when def gets an empty array? @bzorn

**Comment by lemmy** [comment]
> Do we want to throw by default when def gets an empty array? @bzorn

+1 (seems like reasonable behavior)

**Comment by pelikhan** [comment]
Now fails by default when the `files` array is empty.

**Comment by pelikhan** [comment]
Let's see if this is enough.
