### ISSUE TITLE
Expose tree-sitter's query API

### ISSUE THREAD

**Issue by lemmy** [microsoft/genaiscript#292]
tree-sitter comes with a [generic query API](https://tree-sitter.github.io/tree-sitter/using-parsers#pattern-matching-with-queries).   It should be possible to include queries in the prompt and iterate over tree-sitters results. For example:

> For each `block_comment` in INPUT, do ...

**Comment by pelikhan** [comment]
Add through https://github.com/microsoft/genaiscript/pull/313

**Comment by pelikhan** [comment]
https://github.com/microsoft/genaiscript/pull/313
