### ISSUE TITLE
minimum severity flag in cli/script

### ISSUE THREAD

**Issue by pelikhan** [microsoft/genaiscript#303]
To filter out warnings/info messages as needed.

**Comment by lemmy** [comment]
Use cases:
* https://github.com/microsoft/CCF/security/code-scanning/787
* https://github.com/microsoft/CCF/security/code-scanning/792
* https://github.com/microsoft/CCF/security/code-scanning/793
* https://github.com/microsoft/CCF/security/code-scanning/803

**Comment by pelikhan** [comment]
This can be done with defOutput https://github.com/microsoft/genaiscript/issues/304
