### ISSUE TITLE
TLA+ treesitter fails

### ISSUE THREAD

**Issue by pelikhan** [microsoft/genaiscript#314]
Test:

```sh
$ node packages/cli/built/genaiscript.cjs parse code src/tla/EWD998PCal.tla "(local_definition) @i"
```

```
ENOENT: no such file or directory, open 'src/tla/EWD998PCal.tla'
```

**Comment by pelikhan** [comment]
https://github.com/microsoft/genaiscript/pull/315

**Comment by lemmy** [comment]
`yarn install` to generate `packages/cli/built/genaiscript.cjs`

**Comment by lemmy** [comment]
Upgrading tree-sitter-tlaplus.wasm to 1.2.3 gets us:

```shell
markus@avocado [18:24:42] [~/src/genaiscript] [treesittertlaps *]
-> % node packages/cli/built/genaiscript.cjs parse code tcp.tla "(block_comment) @i"
null function or function signature mismatch
```

**Comment by lemmy** [comment]
### Transitive closure of dependencies

| Project | Node Dependency Name | Latest Version |
| -------- | ------- | ------- |
| [tree-sitter](https://github.com/tree-sitter/tree-sitter)  |  | 0.22.2 |
| [tree-sitter-cli](https://github.com/tree-sitter/tree-sitter) | [tree-sitter-cli ](https://www.npmjs.com/package/tree-sitter-cli) | 0.22.2 |
| [node-tree-sitter](https://github.com/tree-sitter/node-tree-sitter) | [tree-sitter](https://www.npmjs.com/package/tree-sitter) | 0.21.1 |
| [tree-sitter-wasms](https://github.com/Gregoor/tree-sitter-wasms) | [tree-sitter-wasms](https://www.npmjs.com/package/tree-sitter-wasms) | 0.1.10 |
| [tree-sitter-tlaplus](https://github.com/tlaplus-community/tree-sitter-tlaplus) | [tree-sitter-tlaplus](https://www.npmjs.com/package/@tlaplus/tree-sitter-tlaplus) | 1.2.3

### Related
* https://github.com/Gregoor/tree-sitter-wasms/pull/31
* https://github.com/Gregoor/tree-sitter-wasms/actions/runs/8520806877
* https://github.com/tlaplus-community/tree-sitter-tlaplus/issues/101
* https://tlaplus-community.github.io/tree-sitter-tlaplus/
* https://github.com/tree-sitter/node-tree-sitter/issues/193
