### ISSUE TITLE
Automatically parsing pdf files in def()

### ISSUE THREAD

**Issue by bzorn** [microsoft/genaiscript#321]
With version 1.17.0 in VS Code marketplace. This is what docs say:
![image](https://github.com/microsoft/genaiscript/assets/5445979/3076cf0f-8ca8-4b58-a789-740399db8c2f)
This is my script:
![image](https://github.com/microsoft/genaiscript/assets/5445979/0b6379da-e2e8-4cbe-bffc-350647d846b2)
When I ran this script on a foo.pdf file, the LLM got this:
![image](https://github.com/microsoft/genaiscript/assets/5445979/fcb78a83-4ddc-4f4d-8486-7fc6c9d71cdb)

**Comment by bzorn** [comment]
Note this is with the VS Code marketplace version of GenAIScript as of 4/3/2024

**Comment by bzorn** [comment]
Issue also occurs with latest build in repo (4/3/2024).

**Comment by bzorn** [comment]
I confirmed that this does work in the current repo version.

**Comment by pelikhan** [comment]
The issue might be that it fails to load the pdf parser library (pdf.js) in the vscode scenario.

**Comment by pelikhan** [comment]
Fixed by https://github.com/microsoft/genaiscript/commit/c70eff53e35bba11c58335e6ef805ebf02656809
