### ISSUE TITLE
Problem installing pdfjs when using parsers.PDF

### ISSUE THREAD

**Issue by bzorn** [microsoft/genaiscript#324]
Type: <b>Bug</b>

## Describe the issue
Error in running the script due to failure to load pdf.js
🧬 prompt
📓 script source
model: gpt-4
temperature: 0.2
❌ pdfjs-dist not found, installing 4.0.379...
install pdfjs-dist@4.0.379
❌ pdfjs-dist failed to load
❌ at prompt line 5, column 18

Contents of script:
```
script({ title: "gen-tweet" })
const { file, pages } = await parsers.PDF(env.files[0])
def("FILE", pages[0])
$`Given the paper in FILE, write a 140 summary of the paper 
and make it spicy.
```

## To Reproduce
Run script over any .pdf file

## Expected behavior
Should parse the document and feed to LLM.  Instead, the process fails before calling the LLM.

## Environment

vscode: 1.87.2
extension: 1.19.1
## Request
`````
## gen-tweet



<details id="🤖-automation" class="genaiscript">
<summary>
🤖 automation
</summary>

This operation can be automated using the command line interface.

- to run on all files at once, use the `run` command:

```bash
npx --yes genaiscript@^1.19.1 run gen-tweet "diehard.pdf" --apply-edits
```

- to run a LLM generation on each file, use the `batch` command:

```bash
npx --yes genaiscript@^1.19.1 batch gen-tweet "diehard.pdf" --apply-edits
```


-   You will need to install [Node.js](https://nodejs.org/en/).
-   The CLI uses the same secrets in the `.env` file.
-   Run `npx genaiscript help run` for the full list of options.

</details>



<details id="📄-spec" class="genaiscript">
<summary>
📄 spec
</summary>


```markdown
# Specification

-   [diehard.pdf](./diehard.pdf)
```

</details>



<details id="💾-script" class="genaiscript">
<summary>
💾 script
</summary>



<details id="🧬-prompt" class="genaiscript">
<summary>
🧬 prompt
</summary>



<details id="📓-script-source" class="genaiscript">
<summary>
📓 script source
</summary>


```js
script({ title: "gen-tweet" })

const { file, pages } = await parsers.PDF(env.files[0])
def("FILE", pages[0])

$`Given the paper in FILE, write a 140 summary of the paper 
and make it spicy.
`        
```

</details>

-   model: gpt-4
-   temperature: 0.2
### ❌ pdfjs-dist not found, installing 4.0.379...



<details id="install-pdfjs-dist@4.0.379" class="genaiscript">
<summary>
install pdfjs-dist@4.0.379
</summary>

-   cwd: c:\Users\zorn\.vscode\extensions\genaiscript.genaiscript-vscode-1.19.1\built
-   shell command: `npm` install --no-save --ignore-scripts pdfjs-dist@4.0.379
-   exit code: NaN


<details id="📩-output" class="genaiscript">
<summary>
📩 output
</summary>


```markdown

```

</details>


</details>

### ❌ pdfjs-dist failed to load

### ❌  at prompt line 5, column 18


```yaml
{}
```

</details>


</details>


`````

Extension version: 1.19.1
VS Code version: Code 1.87.2 (863d2581ecda6849923a2118d93a088b0745d9d6, 2024-03-08T15:20:17.278Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Silver 4108 CPU @ 1.80GHz (32 x 1796)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.71GB (28.47GB free)|
|Process Argv|--crash-reporter-id 2058db1e-f1e8-433e-bf38-476163c306a2|
|Screen Reader|no|
|VM|0%|
</details>

**Comment by pelikhan** [comment]
We might have to resort to using the server for PDFs on windows.
