### ISSUE TITLE
Support file paths in CLI invocations of scripts

### ISSUE THREAD

**Issue by bzorn** [microsoft/genaiscript#349]
Allow paths without quotes, allow paths to inputs.

**Comment by pelikhan** [comment]
could you add examples of what you are trying to do?

**Comment by bzorn** [comment]
Here are some examples of the failure.  I'm in a directory tmp, I have a local .env file (same directory).  I have another directory ..\inputs with 2 pdf files in it.  I'm trying to run a script with the files in inputs as inputs to script.  

> npx --yes genaiscript run .\gen-tweet.genai.js ..\inputs\*.pdf
**no files matching ..\inputs\*.pdf**
> npx --yes genaiscript run .\gen-tweet.genai.js "..\inputs\*.pdf"
**no files matching ..\inputs\*.pdf**

If the files are local to the current directory, it works:  

> npx --yes genaiscript run .\gen-tweet.genai.js *.pdf
prompting model gpt-4
undefined
"Discover GenAIScript: a new language integrating AI into scripting, making LLMs accessible for robust, innovative software development! #AI #Coding"undefined
undefined
"Discover GenAIScript: a new language integrating AI into scripting, making LLMs accessible for robust, innovative software development! #AI #Coding"
genaiscript generated 32 tokens

(Also, not sure where the "undefined" output is coming from)

**Comment by pelikhan** [comment]
Fixed by https://github.com/microsoft/genaiscript/commit/9525ecd25bcec5c6b52cc411fdc47256155a1553
