### ISSUE TITLE
CLI invocation fails on Windows 

### ISSUE THREAD

**Issue by bzorn** [microsoft/genaiscript#351]
I'm running the CLI on my Windows laptop running node version: 
 node --version
v20.11.1
 npm --version
7.5.3

And the package install fails:
> npx --yes genaiscript run test1 "genaisrc/test1.genai.js" --out-trace
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR!
npm ERR! Found: node-fetch@2.7.0
npm ERR! node_modules/node-fetch
npm ERR!   node-fetch@"^2.6.7" from @anthropic-ai/sdk@0.15.0
npm ERR!   node_modules/@anthropic-ai/sdk
npm ERR!     @anthropic-ai/sdk@"^0.15.0" from llamaindex@0.1.21
npm ERR!     node_modules/llamaindex
npm ERR!       optional llamaindex@"0.1.21" from genaiscript@1.19.5
npm ERR!       node_modules/genaiscript
npm ERR!         genaiscript@"*" from the root project
npm ERR!   node-fetch@"^2.6.7" from @mistralai/mistralai@0.0.10
npm ERR!   node_modules/@mistralai/mistralai
npm ERR!     @mistralai/mistralai@"^0.0.10" from llamaindex@0.1.21
npm ERR!     node_modules/llamaindex
npm ERR!       optional llamaindex@"0.1.21" from genaiscript@1.19.5
npm ERR!       node_modules/genaiscript
npm ERR!         genaiscript@"*" from the root project
npm ERR!   3 more (@notionhq/client, cohere-ai, openai)
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peerOptional node-fetch@"^3.3.2" from @llamaindex/cloud@0.0.4
npm ERR! node_modules/@llamaindex/cloud
npm ERR!   @llamaindex/cloud@"0.0.4" from llamaindex@0.1.21
npm ERR!   node_modules/llamaindex
npm ERR!     optional llamaindex@"0.1.21" from genaiscript@1.19.5
npm ERR!     node_modules/genaiscript
npm ERR!       genaiscript@"*" from the root project
npm ERR!
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.
npm ERR!
npm ERR! See C:\Users\zorn\AppData\Local\npm-cache\eresolve-report.txt for a full report.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\zorn\AppData\Local\npm-cache\_logs\2024-04-17T17_04_33_345Z-debug.log

**Comment by pelikhan** [comment]
Add FAQ and more docs in cli in https://github.com/microsoft/genaiscript/pull/350
