### ISSUE TITLE
Provide a more complete list of available system prompts in the documentation

### ISSUE THREAD

**Issue by bzorn** [microsoft/genaiscript#356]
The current docs only give a couple of examples.  It would be good to have a complete list of the ones that are available:
![image](https://github.com/microsoft/genaiscript/assets/5445979/a53eaab3-c2c8-41b2-9eed-912d2b472958)

**Comment by pelikhan** [comment]
Something started. https://github.com/microsoft/genaiscript/pull/357/commits/6e86897aac4ac433836713b359f0356a33bb7c86
