### ISSUE TITLE
Either get rid of .gpspec files or explain them better

### ISSUE THREAD

**Issue by bzorn** [microsoft/genaiscript#367]
We use .gpspec files to create a way to parameterize a script so that the same script can be applied in different contexts by changing what gpspec file is used to instantiate the script.    The main use of gpspec files is to enumerate a list of related files to read into the script context.    We should get rid of gpspec files and explain alternative ways to get the same effect.

**Comment by pelikhan** [comment]
I think we should get rid of them.... before it's too late. We could bring them back.
