### ISSUE TITLE
Need documentation to explain how to apply a GenAIScript to the current project folder in VS Code

### ISSUE THREAD

**Issue by bzorn** [microsoft/genaiscript#371]
If you want to use the right-click context menu to apply a script to the entire project folder, then the VS Code UI doesn't allow it.  We should document that you have to find empty space below the listing in the explorer and right click there.
![image](https://github.com/microsoft/genaiscript/assets/5445979/b8d381f4-2195-43f7-9c71-74cfed7e9ee8)

**Comment by pelikhan** [comment]
Fixed in https://microsoft.github.io/genaiscript/getting-started/running-scripts/
