### ISSUE TITLE
support for system in runprompt

### ISSUE THREAD

**Issue by bzorn** [microsoft/genaiscript#378]
I've got this code in my script:

```
const cleanInfo = await runPrompt(_ => {
    // use def, $ and other helpers
    _.def("INFO", parktext.text)
    _.$`You are an expert in web content. 
    Extract out of the file INFO, which is HTML with lots of CSS and HTML tags, 
    the important information that a human would want to know.`
    },
    { model: "ollama:phi3", system: ["system"]}
)
```

It looks like adding "system" causes an error in the script but when I omit it, the model used to run the runPrompt isn't ollama:phi3.

**Comment by pelikhan** [comment]
runPrompt does not support system scripts yet. There's another issue on this.

**Comment by pelikhan** [comment]
Looks like 2 bugs here. System prompts not supported and model info lost.

**Comment by pelikhan** [comment]
fix for phi3 selection: https://github.com/microsoft/genaiscript/commit/5d80928fda318fc5cd4d7e0500adc77ba218b3fe

**Comment by pelikhan** [comment]
Added
