### ISSUE TITLE
Possible issue with interactive mode

### ISSUE THREAD

**Issue by bzorn** [microsoft/genaiscript#410]
Got this error message when doing "run samples" from codespace instance.
![image](https://github.com/microsoft/genaiscript/assets/5445979/2f74c0fb-54e2-4344-af07-f8611d6ceb2c)

The extension launched successfully.

**Comment by pelikhan** [comment]
so fresh code space and installed addon?

**Comment by pelikhan** [comment]
what do you call "run samples" ?

**Comment by bzorn** [comment]
![image](https://github.com/microsoft/genaiscript/assets/5445979/f365cca4-df6d-4baf-a062-767f60628e24)

**Comment by bzorn** [comment]
I'll try a fresh codespace.  Mine was old but I was synced and did a yarn install prior

**Comment by pelikhan** [comment]
it might not be our error

**Comment by bzorn** [comment]
Could not repro on a fresh codespace instance.
