### ISSUE TITLE
TOC scrolls incorrectly when a selection is made

### ISSUE THREAD

**Issue by tballmsft** [microsoft/genaiscript#441]
1. open https://microsoft.github.io/genaiscript/
2. scroll down in TOC and select some item I 
3. see that page to right displays item I but that TOC scrolls away to some other point
4.

**Comment by pelikhan** [comment]
Yeah, it seems that astro (the doc framework) does not maintain the scroll location when doing a navigation.

**Comment by pelikhan** [comment]
Vote https://github.com/withastro/starlight/pull/1121
