### ISSUE TITLE
where is the workspace rooted?

### ISSUE THREAD

**Issue by tballmsft** [microsoft/genaiscript#442]
What defines the root of a workspace? Please document. This page

https://microsoft.github.io/genaiscript/reference/scripts/files/#workspace

refers to the workspace root, but it is not clear how/where it is defined.

**Comment by pelikhan** [comment]
fixed by https://github.com/microsoft/genaiscript/commit/fd6ad41a5ce85bd587070f639e2277b0616b8ee7
