### ISSUE TITLE
Right click context menu shows "Run Test" and "Debug Test" not Run GenAIScript

### ISSUE THREAD

**Issue by bzorn** [microsoft/genaiscript#458]
Type: <b>Bug</b>

## Describe the issue
<b> Sorry for not being clear.  This issue occurs when I try to right click in the Explorer file view </b>
I want to run a script on a file.  I use the right-click context menu trying to select "Run GenAIScript..." but the only choices I get are "Run Test" and "Debug Test"

Here's a screen shot:
![image](https://github.com/microsoft/genaiscript/assets/5445979/5ea6ddba-0893-4b24-a223-64e40a12f535)

## Environment

vscode: 1.89.1
extension: 1.29.2

Extension version: 1.29.2
VS Code version: Code 1.89.1 (dc96b837cf6bb4af9cd736aa3af08cf8279f7685, 2024-05-07T05:13:33.891Z)
OS version: Windows_NT x64 10.0.22631
Modes:

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Silver 4108 CPU @ 1.80GHz (32 x 1796)|
|GPU Status|2d_canvas: enabled<br>canvas_oop_rasterization: enabled_on<br>direct_rendering_display_compositor: disabled_off_ok<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>opengl: enabled_on<br>rasterization: enabled<br>raw_draw: disabled_off_ok<br>skia_graphite: disabled_off<br>video_decode: enabled<br>video_encode: enabled<br>vulkan: disabled_off<br>webgl: enabled<br>webgl2: enabled<br>webgpu: enabled|
|Load (avg)|undefined|
|Memory (System)|63.71GB (39.52GB free)|
|Process Argv|--crash-reporter-id 2058db1e-f1e8-433e-bf38-476163c306a2|
|Screen Reader|no|
|VM|0%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368cf:30146710
vspor879:30202332
vspor708:30202333
vspor363:30204092
vscod805:30301674
binariesv615:30325510
vsaa593cf:30376535
py29gd2263:31024239
c4g48928:30535728
azure-dev_surveyone:30548225
a9j8j154:30646983
962ge761:30959799
pythongtdpath:30769146
welcomedialogc:30910334
pythonidxpt:30866567
pythonnoceb:30805159
asynctok:30898717
pythontestfixt:30902429
pythonregdiag2:30936856
pyreplss1:30897532
pythonmypyd1:30879173
pythoncet0:30885854
h48ei257:31000450
pythontbext0:30879054
accentitlementst:30995554
dsvsc016:30899300
dsvsc017:30899301
dsvsc018:30899302
cppperfnew:31000557
d34g3935:30971562
fegfb526:30981948
bg6jg535:30979843
ccp2r3:30993541
dsvsc020:30976470
pythonait:31006305
gee8j676:31009558
showvideoc:31016891
chatpanelc:31018788
dsvsc021:30996838
jg8ic977:31013176
pythoncenvpt:31022790

```

</details>

**Comment by pelikhan** [comment]
What file are you trying this one?

**Comment by bzorn** [comment]
Note that the right click context menu works when you invoke it from inside the file.  
![image](https://github.com/microsoft/genaiscript/assets/5445979/af08f99d-bd50-4fd7-a6f6-7a6ad15e8d7b)

**Comment by bzorn** [comment]
When I'm in the Explorer and I use the right click to get the Context Menu, the Run Tests appears on every file I click on.

**Comment by pelikhan** [comment]
I'll need more details where exactly you are right clicking in the UI

**Comment by bzorn** [comment]
I'm in the file explorer in VS Code, and right clicking on a file that I want to run a script on.  Here's a view:
![image](https://github.com/microsoft/genaiscript/assets/5445979/effe3271-0afd-4319-9ac6-db42d9905d37)
Instead of getting the choice "Run GenAIScript..." I see the choice "Run Test".

**Comment by bzorn** [comment]
Sorry my bad.  Because the "Run GenAIScript..." menu item occurs at the end of a long list, it was scrolled out of view.
