### ISSUE TITLE
defData fails without empty options parameter

### ISSUE THREAD

**Issue by bzorn** [microsoft/genaiscript#474]
When processing portions of an Excel file, defData fails without {} parameter:

const sheets = await parsers.XLSX(env.files[0])
const { rows } = sheets[0]
const rows10 = rows.slice(0, 10)
console.log("rows10", rows10)   

defData("SSSUMMARY",rows10, {})

**Comment by pelikhan** [comment]
fix for https://github.com/microsoft/genaiscript/commit/45de0141b0b64a2e97c4d36291d51930b99551b0
