### ISSUE TITLE
Vscode Insiders Copilot

### ISSUE THREAD

**Issue by shism2** [microsoft/genaiscript#489]
There is mention here that we can use Copilot but I can't seem to get it to show up as an option. https://microsoft.github.io/genaiscript/reference/token/#visual-studio-code-language-models-insiders-only

**Comment by pelikhan** [comment]
Here are more detailled instructions: https://microsoft.github.io/genaiscript/getting-started/configuration/#vscode-copilot-insiders

**Comment by shism2** [comment]
I already followed the instructions and it the option to choose copilot doesn't appear.

**Comment by pelikhan** [comment]
I assumed the instructions fixed it.:)

**Comment by pelikhan** [comment]
We do not have a special build for insiders anymore.
