### ISSUE TITLE
System prompt for "verbose" output 

### ISSUE THREAD

**Issue by bzorn** [microsoft/genaiscript#562]
Sometimes you want the model to explain its output with greater clarity.  Have a special "explain" system prompt for that.  Maybe also add a --verbose option to the command line version that inserts this for debugging purposes.

Also, in the "explain" prompt, ask the model to quote from the input to make its explanations concrete.

**Comment by pelikhan** [comment]
So you could use env.vars.explain and set that flag in the cli


    if (env.vars.explain)
      $`Explain your reasoning`

then

    genaiscript ... --vars explain=true

**Comment by bzorn** [comment]
Sounds like a good approach. Closing since it is easy for users to implement on their own.

**Comment by pelikhan** [comment]
Let's add a doc page on this
