### ISSUE TITLE
Specifying model: "gpt-4" isn't working

### ISSUE THREAD

**Issue by bzorn** [microsoft/genaiscript#654]
Previously, I was able to say model: "gpt-4" and the code would infer I meant "openai:gpt-4"
Now, when I say model: "gpt-4" I get an error message saying model not found.
Either docs or code should be updated.

**Comment by pelikhan** [comment]
```
script({ title: "test1", 
    model: "gpt-4", 
    group: "text", 
    system: ["system"]})
    
$`What city is Abbey Delray in?`
```
