### ISSUE TITLE
Vision model not supported

### ISSUE THREAD

**Issue by zhengshuai1001** [microsoft/genaiscript#804]
![Image](https://github.com/user-attachments/assets/3c129303-1071-4ed0-a7c1-c46e8f197010)

**Comment by pelikhan** [comment]
The 'client:gpt-4o' uses the models provided as part of visual studio copilot chat. This "route" does not support vision.

You'll need to use a deployment of gpt-4o that supports vision; either through github models (`github:gpt-4o`) or Azure OpenAI or Azure AI Serverless.

![Image](https://github.com/user-attachments/assets/0e9bd6b4-1019-4fc3-9cbc-f61b795f43b0)

**Comment by zhengshuai1001** [comment]
Thanks♪(･ω･)ﾉ
