### ISSUE TITLE
document how to access hugging face

### ISSUE THREAD

**Issue by sciabarracom** [microsoft/genaiscript#819]
On the web is mentioned the "provider": "huggingface", however it is no more possibile to specify a provider in the `script` options.

HuggingFace inference should be similar to OpenAI however looks like the token is not passed properly.

With those two varaibles:

```
HUGGINGFACE_CODELLAMA_CODELLAMA_34B_INSTRUCT_HF_API_TOKEN=hf_your_token
HUGGINGFACE_CODELLAMA_CODELLAMA_34B_INSTRUCT_HF_API_BASE=https://api-inference.huggingface.co/v1/
```

and this script: ```$`generate the fibonacci function in python` ```

It works ONCE, then you get this error:

```
$ npx codegenai fib  --model huggingface:deepseek-ai/DeepSeek-Coder-V2-Instruct
retry #1 in 1s, 429, Too Many Requests
retry #2 in 1.6s, 429, Too Many Requests
retry #3 in 2.3s, 429, Too Many Requests
```

If I use the token with python it works so looks like it is problem of authentication.

**Comment by sciabarracom** [comment]
Closing the issue as the problem turned out to be I have to use `API_KEY` not token,
also the model is unnecessary, so I solved setting:

```
HUGGINGFACE_API_KEY
HUGGINGFACE_API_BASE
```

**Comment by pelikhan** [comment]
Let me dig through this scenario and maybe add a bit more docs

**Comment by pelikhan** [comment]
@sciabarracom  documented at https://microsoft.github.io/genaiscript/getting-started/configuration/#huggingface . good enough?

**Comment by sciabarracom** [comment]
Definitely yes thanks.
