### ISSUE TITLE
Bug: GenAI script making changes to every git repo opened (even if not used)

### ISSUE THREAD

**Issue by sammcj** [microsoft/genaiscript#820]
After installing the GenAIScript VSCode extension every code repo I open in VSCode has two new files created:

```
 create mode 100644 .genaiscript/.gitattributes
 create mode 100644 .genaiscript/.gitignore
```

This occurs even if GenAIScript was not used in the repo or even the VSCode session.

This is an issue as users will not want to make changes to every git repo they contribute to for one extension they happen to have installed.

**Comment by pelikhan** [comment]
Yes that's not the intended behavior. It should only do this when finding .genai.mjs files.

**Comment by sammcj** [comment]
Thanks :)
