### ISSUE TITLE
global configuration

### ISSUE THREAD

**Issue by pelikhan** [microsoft/genaiscript#838]
Add support for a configuration file that contains common configuration flags

**Comment by pelikhan** [comment]
https://github.com/microsoft/genaiscript/pull/858

**Comment by borgius** [comment]
VSCode still don't list global scripts

**Comment by pelikhan** [comment]
Right, that part still needs work.

**Comment by pelikhan** [comment]
Fixed in https://github.com/microsoft/genaiscript/pull/893

**Comment by pelikhan** [comment]
support added in 1.78.3
