### ISSUE TITLE
User-friendly way for Serving and Calling AI Scripts via API

### ISSUE THREAD

**Issue by jamespacileo** [microsoft/genaiscript#847]
Thank you for your hard work on this library—it has been incredibly helpful for creating quick AI scripts and drafting new behaviors.

I was wondering if there’s currently a way to serve these scripts via an API, allowing them to be accessed programmatically by importing a client and calling the scripts directly. This would greatly streamline integration and expand the library's usability for automated workflows.

Thank you again for your time and assistance!

**Comment by pelikhan** [comment]
@jamespacileo currently, you could call the CLI and get the full JSON report back (using the --json flag). It's a bit heavy but it gets things done. We could have a JS/Py wrapper around this; even a dockerized version.

Another solution would be to spin up the server that VSCode uses and talk to it. It'll have a faster startup time and it's only websockets.

**Comment by pelikhan** [comment]
tracking in https://github.com/microsoft/genaiscript/issues/847
