### ISSUE TITLE
TypeChat integration

### ISSUE THREAD

**Issue by pelikhan** [microsoft/genaiscript#849]
Integrate or replcaite TypeChat like reflection where one can define a schema from a type instead of JSON schema.

**Comment by enoch3712** [comment]
@pelikhan Best option as discussed:

https://microsoft.github.io/genaiscript/guides/zod-schema/

**Comment by pelikhan** [comment]
So the issue with Zod is that we bundle all the type information in genaiscript.d.ts and I don't know how much typescript definition we would need to make it work. What we really want is a mini-Zod like library that only supports the subset of JSON schemas defined in genaiscript 

(JSON schema can be more complex than what LLM can typically handle)

**Comment by pelikhan** [comment]
But yeah a runtime api to build a schema in a fluent way would be noice

**Comment by pelikhan** [comment]
We have a runtime file now so we could ship a zod helper/wrapper

**Comment by pelikhan** [comment]
https://github.com/microsoft/genaiscript/pull/963

**Comment by pelikhan** [comment]
zod support added.
