### ISSUE TITLE
Issue Saving a GenAiScript Markdown Notebook

### ISSUE THREAD

**Issue by pl-shernandez** [microsoft/genaiscript#865]
I'm having an issue saving a new notebook in VS Code to my file system.

When I run the command palette command it creates a default tutorial populated notebook with a name like 'Untitled-2'. 

But when I go to save within my repository for example as `notebook.md `I get the error shown. 

![Image](https://github.com/user-attachments/assets/45c82edd-39ff-45d2-9410-86984d63bcde)
![Image](https://github.com/user-attachments/assets/84e35fc9-1a6f-4024-bbdc-fe80d1d8dc7e)

- VS Code Version: 1.95.3 (Universal)
- Extension: GenAIScript v1.75.2
- npm package: "genaiscript": "^1.74.1"
- MacOS: Sonoma 14.6.1

**Comment by pelikhan** [comment]
Fix coming in the 1.75.3

**Comment by pl-shernandez** [comment]
Thanks so much!

**Comment by pelikhan** [comment]
Thanks for the report!
