### ISSUE TITLE
Test / promptfoo Issues

### ISSUE THREAD

**Issue by pl-shernandez** [microsoft/genaiscript#872]
# Issue

I'm having some issues getting the `test` functionality to succeed so I stripped it down to a very simple script. The issue is when using any of `npx genaiscript test add`, right-clicking the script and choosing "Run Tests" or via the VS Code Test Explorer. My teammate is experiencing the same issue.

# Script
I made this barebones script which works just fine when ran and I know that the model is deployed.
```
genaiscript: add
prompting azure:gpt-4o (~245 tokens)

1 + 1 equals 2.

genaiscript: success
```

`add.genaiscript.mjs`
```
script({
  title: 'Simple Math Test',
  description: 'Validates that the model correctly calculates 1+1.',
  group: 'Basic Tests',
  temperature: 0,  
  model: 'azure:gpt-4o',
  maxTokens: 10, 
  tests: [
    {
      files: [],  
      rubrics: ['output correctly calculates 1+1 as 2'],
      facts: [`The model should return "2".`],
      asserts: [
        {
          type: 'equals',
          value: '2', 
        },
      ],
    },
  ],
});

$`What is 1 + 1?`;  
```
# Errors 
The errors I receive in the terminal when running via right-clicking the script or Test Explorer...
```
❌ add Command failed with exit code 1: npx --yes 'promptfoo@0.94.5' eval --config .genaiscript/tests/add.promptfoo.yaml --max-concurrency 1 --no-progress-bar --cache --verbose --output .genaiscript/tests/add.promptfoo.res.json http://127.0.0.1:15500/eval?evalId=eval-gtY-2024-11-18T19%3A59%3A59
```
and in the PromptFoo UI
![Image](https://github.com/user-attachments/assets/b6e5efcc-b95b-4495-9e63-9626708c228c)

Similarly if i run `npx genaiscript test add`
![Image](https://github.com/user-attachments/assets/c3ae41ea-7abf-45a9-be90-97152f15a44f)

# Troubleshooting
I tried adding additional variables for the default models in my `.env` but that didn't help
AZURE_OPENAI_API_KEY=hidden
AZURE_OPENAI_API_ENDPOINT=hidden
GENAISCRIPT_DEFAULT_MODEL="azure:gpt-4o"
GENAISCRIPT_DEFAULT_SMALL_MODEL="azure:gpt-4o"
GENAISCRIPT_DEFAULT_VISION_MODEL="azure:gpt-4o"

Tried adding `promptfoo` as a dependency
`npm install -d promptfoo@latest`

Tried un-installing and re-installing extension

# Setup
genaiscript": "^1.76.0
vscode: Version: 1.95.3 (Universal)
mac os: 14.6.1 

# Going Further
Prior to this I was able to runs some more complex prompts with tests unsuccessfully using an augmented version of the poem example. But I received unterminated JSON errors even with 4096 tokens set. I felt I should try and ask for help on this first.

**Comment by pelikhan** [comment]
I suspect we leak some logging in the console.out that breaks the console.log

I will investigate.

**Comment by pelikhan** [comment]
(The formatting is unfortunate in promptfoo but there is no way to customize how it is rendered in the cli)

**Comment by pelikhan** [comment]
The issue is that rubrick or facts are LLM-as-judge type of assertions and they require further configuration of the LLM. This is not well supported by genaiscript yes (oops). The promptfoo docs are at https://www.promptfoo.dev/docs/configuration/expected-outputs/model-graded/llm-rubric/#overriding-the-llm-grader for info.

To debug further the promptfoo issues, you can take a look at the .yml files dropped under `.genaiscript/tests/*.yml`. These are promptfoo configuration that are run directly by the promptfoo cli. For those, all the docs at https://www.promptfoo.dev/docs/getting-started/ apply since GenAIScript is merely launching the promptfoo cli on those. This is usually how I debug promptfoo.

**Comment by pelikhan** [comment]
I need to add an escape hatch to allow for configuration the promptfoo grader.

**Comment by pelikhan** [comment]
Thank you for the investigation. I'll be looking into the mods.

**Comment by pelikhan** [comment]
- remoiving cache https://github.com/microsoft/genaiscript/commit/187da713cd8cc5043e7d75b4e4d9f2c6bae1aa94

**Comment by pelikhan** [comment]
Please try 1.77.3 and above. Cache is gone and the configuration in the generate .yml file is more precise. You'll still need the .env variables. I'll see about supporting them in GenAIScript as well so you don't have to duplicate them.

**Comment by pl-shernandez** [comment]
Awesome! Just tried this out in 1.78.2 and it works! I was able to click run test and it executed successfully and I only need the three environment variables set at a minimum. 

![Image](https://github.com/user-attachments/assets/0b6130b2-cf1d-484c-8eb3-d02f77ee20a6)

```
AZURE_OPENAI_API_KEY= 
AZURE_OPENAI_API_ENDPOINT= 
GENAISCRIPT_DEFAULT_MODEL="azure:gpt-4o"
```

Running via the command line with `npx genaiscript test add` also works ![Image](https://github.com/user-attachments/assets/e11d852c-73bf-4825-bcdf-a2ca6289ccde)

**Comment by pelikhan** [comment]
Thanks for validating!
