### ISSUE TITLE
Running a git command against a different context

### ISSUE THREAD

**Issue by sahuguet** [microsoft/genaiscript#874]
I understand that GenAIScript design philosophy is to attach a script to a given folder, either when calling from VS Code or via the CLI.

Not being a fan of git modules, I am looking for a way to create a GenAIScript I can run against any git repo I want, e.g. by specifying the location of the repo using `--vars`. 

I could not find a way to have the git command run outside of the current directory. Am I Missing something?

The workaround I have found is to import the `zx` package (see https://github.com/microsoft/genaiscript/discussions/873) and run arbitrary commands like `cd my-git-repo; git log -20`.

**Comment by pelikhan** [comment]
The tools also assume the current repo but we could add an option to override that. As long as it does not confused the LLM...
