### ISSUE TITLE
Calling GenAIScript from inside my own app

### ISSUE THREAD

**Issue by sahuguet** [microsoft/genaiscript#875]
I am a big fan of GenAIScript.
It is like having a a spell book at your fingertips.

I am fine with the CLI interface. But I can see a lot of value for less technical users who need to perform common tasks like summarization of local documents, summarization of news every day, etc.

For this kind of users, VS Code is going to be overkill.

Is it possible to build an app (I am thinking Electron, but it could be more lightweight) that provides an interface on top of GenAIScript.
- one could drag and drop some files and then run a GenAIScript.
- one could organize their scripts (I mean spells), local and/or remote, and run them
- the app could even provide some kind of cron functionality

Totally crazy?
Totally out of scope?

**Comment by pelikhan** [comment]
One possible options we were thinking about was to provide a builtin web frontend with the server that would provide a simple gradiolike interface for all scanned prompts in the repo. Basically, we would mount a HTML form based on the script parametesr + something special to select files, and render the output/trace.

That way, a non-expert user would easily be able to run the scripts without any knownledge of vscode.

**Comment by pelikhan** [comment]
Open to suggestions!

**Comment by sahuguet** [comment]
For Electron or https://www.electrobun.dev/ which looks interesting too.
