### ISSUE TITLE
`genaiscript parse html-to-text` output is broken

### ISSUE THREAD

**Issue by mattpowell** [microsoft/genaiscript#891]
When running the the `html-to-text` parser via cli the output is:
```
$> npx genaiscript parse html-to-text demo.html
Promise { <pending> }
```

I believe this issue was introduced in this [commit](https://github.com/microsoft/genaiscript/commit/ee96802f0c9ec249384ae0bc45a2414935671a7d#diff-47bfc20a9c2693dfdd110bd62894957ce2d95435969a2b118356d71d8913ccd1R29) when the various HTML functions were converted to async.

And I think it can be resolved by adding an `await` to the `HTMLToText` call [here](https://github.com/microsoft/genaiscript/blob/d3c016cbfc980fc0dd7ed775c721700b76129749/packages/cli/src/parse.ts#L107).

Let me know if additional info is needed or if I can test anything on my end.

Thanks!

**Comment by pelikhan** [comment]
Thanks for the analysis! Fixed in https://github.com/microsoft/genaiscript/commit/a8a908d2959428d1ecc67b82f89f8f69d124f2b8 .

**Comment by pelikhan** [comment]
you can test it out in 1.78.3 @mattpowell

**Comment by pelikhan** [comment]
@mattpowell jsxmin is quite cool; it'd be interresting to get a lightweight jsx syntax for prompt (well there's also priompt and vscode/prompt-tsx but hey).
