### ISSUE TITLE
"Assertion Failed Error" Toaster When Running Script For Version > 1.78.2

### ISSUE THREAD

**Issue by pl-shernandez** [microsoft/genaiscript#906]
I'm having issues running my scripts when the version and extension pair are greater than version `1.78.2` 
If I click the icon and choose "Run GenAiScript.." or Debug I get a toaster error for Assertion Failed. The script isn't able to run.

![Image](https://github.com/user-attachments/assets/dac060ea-6d7f-4115-ace2-aa507b6ceff0)

I'm having the issue and so is my coworker on Windows. However another hadn't updated past 1.76.0 so they didn't notice the issue so that led me down this path.

Is there any other troubleshooting info I can share that might help?

# Troubleshooting
Tried clearing all temporary folders and files 

Used "Install Specific Version..." of extensions and `npm install genaiscript@{version}` until I found the match that works.

I've tried testing with a few scripts just using the npx command rather than extension successfully regardless 
`npx genaiscript@1.80.0 run add`
`npx genaiscript@1.78.2 run add`
 
# Setup
genaiscript: 1.78.2
genaiscript extension: 1.78.2
vscode: Version: 1.95.3 (Universal)
mac os: 14.6.1

**Comment by pl-shernandez** [comment]
⬆️🙃The debug console is empty

**Comment by pelikhan** [comment]
looking

**Comment by pelikhan** [comment]
fix in https://github.com/microsoft/genaiscript/commit/c6672ef240f6c663322e09e9e94c425587b0b1c2

**Comment by pelikhan** [comment]
fixed in 1.80.3

**Comment by pl-shernandez** [comment]
🥳 Yep that solved it -- is well thanks yet again!

**Comment by Swatkins18** [comment]
Hi @pelikhan , I'm on a Windows machine, have the latest VS Code extension for GenAI Script (1.80.3) and now see the "Script not found" error toast when I try to run this simple script using the GenAI Script button. However, I am able to run the script from the command line with the latest version.
![Image](https://github.com/user-attachments/assets/8c458153-37e2-4554-9765-e9598793be76)

**Comment by pelikhan** [comment]
I really need to normalize both file names. Looking

**Comment by pelikhan** [comment]
@Swatkins18 try 1.80.4

**Comment by Swatkins18** [comment]
`1.80.4` fixed the issue for me, thank you @pelikhan !

**Comment by Swatkins18** [comment]
@pelikhan I'm sorry, I wasn't thorough. `1.80.4` fixed using the Run mode but not Debug mode. @pl-shernandez and I are still seeing the "Assertion failed" toast when attempting to run in Debug mode.

**Comment by pelikhan** [comment]
fixed in 1.80.5

**Comment by Swatkins18** [comment]
Thank you! I tested both Run and Debug and they both worked for me!

**Comment by pl-shernandez** [comment]
@pelikhan You're gonna strangle me...

When I do a debug with 1.80.5 on various scripts I get a missing file error. I tried initializing everything I could think of and reinstalling extensions and packages and so on.

Debug Console: 
```
trace: /Users/shernandez/GitHub/centrix-serpent/generative/.genaiscript/runs/add/2024-12-04T21-41-03-385Z.trace.md
genaiscript.cjs:72599
file not found: /response_29/0
```

![Image](https://github.com/user-attachments/assets/b86678d6-b996-4e23-8cb6-a3a4db28cc45)

**Comment by pelikhan** [comment]
I'm gonna have to hug you. haha. let me see if i can repro it.

**Comment by pelikhan** [comment]
It turns out some of the views are now treated as "visibleTextEditors" and sent to the debugger. Adding more debugging and filtering.

**Comment by pelikhan** [comment]
Another round of test for v1.80.9

**Comment by pelikhan** [comment]
let's see if this one stays closed :)

**Comment by Swatkins18** [comment]
Thank you! I have updated to version `1.80.10` and can run my script in both Run and Debug modes without issue. Hopefully it also works for @pl-shernandez 🤞🏻

**Comment by pl-shernandez** [comment]
Confirmed working great 👍 
![Image](https://github.com/user-attachments/assets/36c44467-bc84-417f-8a13-cc72c03e2ac5)
