### ISSUE TITLE
Support for anyOf in JSONSchema

### ISSUE THREAD

**Issue by waltoss** [microsoft/genaiscript#913]
OpenAI JSON supports [anyOf](https://platform.openai.com/docs/guides/structured-outputs#for-anyof-the-nested-schemas-must-each-be-a-valid-json-schema-per-this-subset), it should be part of the typing

```typescript

type JSONSchemaType =
    | JSONSchemaString
    | JSONSchemaNumber
    | JSONSchemaBoolean
    | JSONSchemaObject
    | JSONSchemaArray
    | JSONSchemaAnyOf
    | null

type JSONSchemeAnyOf = {
    anyOf: JSONSchemaType[]
}

```

What do you think ?

**Comment by pelikhan** [comment]
In 1.82.0 (download from releases)
