### ISSUE TITLE
Implement Anthropic caching save tokens

### ISSUE THREAD

**Issue by waltoss** [microsoft/genaiscript#923]
Anthropic added a caching mechanism on messages to save tokens in long conversation
See https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching

Implementation starts with changing

```typescript
// anthropic.ts
        const stream = anthropic.messages.stream({
```

into

```typescript
// anthropic.ts
        const stream = anthropic.beta.promptCaching.messages.stream({
```

**Comment by pelikhan** [comment]
Should it be always on? I think anthorpic disables it automatically for short prompts

**Comment by pelikhan** [comment]
@waltoss  take a look at

https://github.com/microsoft/genaiscript/pull/924
