### ISSUE TITLE
Clarify google model provider limitations (OpenAI compatibility layer vs. GenAIScript)

### ISSUE THREAD

**Issue by AlexandreBouffard** [microsoft/genaiscript#926]
GenAIScript documentation for google model provider does not mention any limitation on its side except for OpenAI compatibility layer limitations, however I faced the following limitations:

### Seed
Specifying a seed results in `genaiscript: error LLM error (400): Bad Request`. GenAIScript could simply ignore seed parameter if it is not supported by google model provider instead of raising an error?

### Function calling
Trying to use function calling results in:

- Empty output with models gemini-1.5-flash, gemini-1.5-pro and gemini-exp-1114.
- Output without any function calling with model gemini-exp-1206.

Google OpenAI compatibility layer should support function calling according to their documentation, so I was wondering if there was a limitation on GenAIScript side?

Thanks!

**Comment by AlexandreBouffard** [comment]
A third limitation (note: all 3 limitations are only with the google model provider, not having them with `chat:` or `azure:` providers):

### Second system message overwriting first system message

When the llm chat starts with 2 system messages, the first one is ignored. Not sure if this is a limitation with OpenAI compatibility layer or GenAIScript.

**Comment by pelikhan** [comment]
> A third limitation (note: all 3 limitations are only with the google model provider, not having them with `chat:` or `azure:` providers):
> 
> ### Second system message overwriting first system message
> When the llm chat starts with 2 system messages, the first one is ignored. Not sure if this is a limitation with OpenAI compatibility layer or GenAIScript.

Good spotting! I'll add a test for this and collapse the system messages. (they should be collapse already).

**Comment by pelikhan** [comment]
> seed

This is a tough one. The default behavior of `seed` is undefined, so one could argue that if the seed is specified -- you really want it to be used.  Hence the error is the correct behavior. Now on the other hand, it makes it harder to use different models.

> tools

It's most likely bug.

**Comment by pelikhan** [comment]
It seems that tools are not fully supported yet. https://discuss.ai.google.dev/t/multi-turn-tool-usage-with-gemini-openai/53202

**Comment by pelikhan** [comment]
The google provider is now using fallback tools ... until full support is back.

**Comment by pelikhan** [comment]
> A third limitation (note: all 3 limitations are only with the google model provider, not having them with `chat:` or `azure:` providers):
> 
> ### Second system message overwriting first system message
> When the llm chat starts with 2 system messages, the first one is ignored. Not sure if this is a limitation with OpenAI compatibility layer or GenAIScript.

do you have a repro?

**Comment by pelikhan** [comment]
> A third limitation (note: all 3 limitations are only with the google model provider, not having them with `chat:` or `azure:` providers):
> 
> ### Second system message overwriting first system message
> When the llm chat starts with 2 system messages, the first one is ignored. Not sure if this is a limitation with OpenAI compatibility layer or GenAIScript.

Now collapsing system messages when rendering prompt

**Comment by pelikhan** [comment]
Try the fixes in v.13.4

**Comment by pelikhan** [comment]
comig in a few minutes

**Comment by AlexandreBouffard** [comment]
Tried v1.83.4:

- [ ] Seed: Specifying a seed still results in same error message with google provider
- [x] Tools: I confirm google provider is now using fallback tools
- [x] System messages: I confirm system messages are now collapsed

**Comment by pelikhan** [comment]
@AlexandreBouffard do you have a repro for the seed? My test case passes.

```
$ node packages/cli/built/genaiscript.cjs run seed --model google:gemini-1.5-pro-latest
genaiscript: seed
 large: google:gemini-1.5-pro-latest
 small: azure:gpt-4o-mini_2024-07-18
 vision: azure:gpt-4o_2024-08-06
 embeddings: openai:text-embedding-ada-002
 reasoning: azure:o1-preview_2024-09-12
trace: /workspaces/genaiscript/.genaiscript/runs/seed/2024-12-10T16-02-04-012Z.trace.md
prompting google:gemini-1.5-pro-latest (~213 tokens)

seed: disabled, not supported by google
In realms of logic, a world unseen,
Where symbols dance and functions convene,
A tapestry woven, intricate and vast,
...
```

**Comment by AlexandreBouffard** [comment]
@pelikhan Interesting, `seed: 123456789` (as in your test case) passes, `seed: 0` fails (it passes with other providers).

**Comment by pelikhan** [comment]
ha! that's just me being silly. I should be checking seed with isNaN and not just !.

**Comment by pelikhan** [comment]
fix in https://github.com/microsoft/genaiscript/commit/3d467b16b456d9045074e8472f70e063ab9edb4e

**Comment by AlexandreBouffard** [comment]
@pelikhan haha! yeah "!" is cleaner but comes biting you when you least expect it ;-)

Great work on this project by the way!

**Comment by pelikhan** [comment]
try again with v1.84.0

**Comment by pelikhan** [comment]
3rd time is the charm

**Comment by pelikhan** [comment]
The OpenAI seems to have a lot of shortcomings, it's probably time to support the native sdk, like for Anthropic.

**Comment by AlexandreBouffard** [comment]
> try again with v1.84.0

All good!
