### ISSUE TITLE
Support for Claude Prompt Caching

### ISSUE THREAD

**Issue by anrgct** [microsoft/genaiscript#927]
I hope to enhance Claude's prompt caching feature, which is very useful for large-scale code analysis. 
I want to complain a bit. It's frustrating that any modification to the order or characters of the cached prompts can invalidate the cache. Additionally, it's unclear why cache points need to be marked separately...
https://docs.anthropic.com/en/docs/build-with-claude/prompt-caching
https://openrouter.ai/docs/prompt-caching

**Comment by pelikhan** [comment]
Prompt caching is implemented: https://microsoft.github.io/genaiscript/reference/scripts/prompt-caching/

I suggest reaching out to Anthropic to change their caching behavior.

**Comment by anrgct** [comment]
It was updated yesterday! Thank you for adding this feature right away! I updated genaiscript@1.83.4, and I found a small issue:  
```
// This one does not work  
def("FILE", env.files, { cacheControl: "ephemeral" })  
// This one works  
Summarize all files in FILE in a single paragraph. `.cacheControl("ephemeral")
```

**Comment by pelikhan** [comment]
Fixed in next release. For now do `def(...., { ephemeral: true })`

**Comment by anrgct** [comment]
thank you!👍

**Comment by anrgct** [comment]
Sorry, I upgraded to v1.86.4, and this issue still exists. It seems to be because ephemeral is not passed to children.
```diff
// packages/core/src/promptdom.ts
...
        def: async (n) => {
            try {
                names.add(n.name)
                const value = await n.value
                n.resolved = value
                n.resolved.content = extractRange(n.resolved.content, n)
                const rendered = renderDefNode(n)
                n.preview = rendered
                n.tokens = estimateTokens(rendered, encoder)
+               let defOption = {};
+               if (n.ephemeral) {
+                    defOption = { ephemeral: true };
+               }
+               n.children = [createTextNode(rendered, defOption)];
-               n.children = [createTextNode(rendered)]
            } catch (e) {
                n.error = e
            }
        },
```

**Comment by pelikhan** [comment]
fixed in 1.87

**Comment by anrgct** [comment]
Changed back to this definition `def("FILE", env.files, { cacheControl: "ephemeral" })`, I upgraded to v1.87 and it worked, thank you!

**Comment by pelikhan** [comment]
cachecontrol is closer to the anthropic message. Maybe more future proof.
