### ISSUE TITLE
Could not find a GenAiScript ....This is most likely a bug in GenAIScript

### ISSUE THREAD

**Issue by partmachine** [microsoft/genaiscript#930]
I installed the GenAI extension, followed the installation and configuration instructions but vscode keeps giving me this error:
"Could not find a GenAiScript d:\development\repos\GenAiProjects\genaisrc\poem.genai.mjs. This is most likely a bug in GenAIScript.|"

**Comment by partmachine** [comment]
The path is correct and the file exists:

[cid:482241de-c0e5-46b1-aa3c-3276fbb49cb2]

________________________________

**Comment by pelikhan** [comment]
Oh disreguard the annoying bot, this definitely looks like a bug on our side. I will test this path on windows.

**Comment by pelikhan** [comment]
Fix or more error logging I. 1.84.1

**Comment by pelikhan** [comment]
Probably fix https://github.com/microsoft/genaiscript/pull/937

**Comment by pelikhan** [comment]
Please try again in v1.84.3

**Comment by partmachine** [comment]
Hi Peli, thanks for picking  this up.
I upgraded to v1.84.3, unfortunately it's still the same: 
![Image](https://github.com/user-attachments/assets/4236b4d6-33f7-416c-97d1-c83f9e367350)

![Image](https://github.com/user-attachments/assets/c287d9f1-048b-48b9-9bc5-6aa7fa5fde75)

**Comment by partmachine** [comment]
The following screenshot show the scripts tab, the folder(?) my file is in says 'unassigned' it also has a unfamiliar icon, when I click the it the file doesn't open but an error is shown in the left bottom corner (screenshot 2).

![Image](https://github.com/user-attachments/assets/3bc0a671-76b9-4c68-a740-1ef9a2523214)
![Image](https://github.com/user-attachments/assets/b22e1811-8be1-4d03-ac24-3f5466ad9a0c)

**Comment by pelikhan** [comment]
I see ...GenAiProject\GenAIproject.. so it seems that I messing when mangling the relative back into a full path. Getting closer

**Comment by pelikhan** [comment]
Are you using multiple workspaces? Are you using vscode desktop/web/codespace?

**Comment by pelikhan** [comment]
Try again with v1.83.4. If it fails, it should drop more info to the GenAIScript output pane.

**Comment by partmachine** [comment]
I'm using vscode desktop, single workspace, v1.8.4 :
![Image](https://github.com/user-attachments/assets/da7a3db2-e140-4fb6-b870-4f8c8ae9f1bb)
 Not seeing a GenAI output pane:
![Image](https://github.com/user-attachments/assets/6b9ce13b-92b2-4fb7-8aad-8ad952bd2436)
Still the same error.

**Comment by pelikhan** [comment]
![Image](https://github.com/user-attachments/assets/bdd79389-a159-4b0a-a14e-a58200b5380c)

or click on the 'report issue' as it also adds information.

**Comment by partmachine** [comment]
Found it, but unforunately still get an error:
![Image](https://github.com/user-attachments/assets/3b9a6204-0952-4a8a-908e-81f904d04cdf)

**Comment by pelikhan** [comment]
Adding more logging :)

**Comment by partmachine** [comment]
Indeed seeing more logging, unfortunately:
![Image](https://github.com/user-attachments/assets/f2d41c13-c073-4c54-8114-91262d977292)

**Comment by pelikhan** [comment]
Great this gives a bit more hints about what's going on. There's a double folder in the middle of the path.

**Comment by pelikhan** [comment]
Try 1.84.8 . If not working feed me back the logs :)

**Comment by partmachine** [comment]
Sorry, I missed 1.84.8, now on 1.85, still the same but my file doesn't open anymore:
![Image](https://github.com/user-attachments/assets/b9de8477-0879-4c9e-ae35-621a0e01fa56)

**Comment by pelikhan** [comment]
Are you trying to run it from the editor?

**Comment by pelikhan** [comment]
This error is different. I think we're making progress. Is there anything special in the project file structure? I will push more logging :)

**Comment by partmachine** [comment]
Hi Peli, apologies for the late reply, I had to attend a funeral, I've included a zipped version of the project, not sure if it will upload though.
[GenAiProjects.zip](https://github.com/user-attachments/files/18135139/GenAiProjects.zip)

**Comment by pelikhan** [comment]
Sorry to hear that. Take care.

**Comment by pelikhan** [comment]
I've pushed another attempt at fixing this in 1.85.1. The CLI now returns absolute paths so hopefully we don't get into a relative path confusion.

**Comment by partmachine** [comment]
Hi Peli, yes! it's working now, thanks a lot

**Comment by pelikhan** [comment]
Thanks for hanging on!
