### ISSUE TITLE
Suggestion : Implement Feature toggling per model

### ISSUE THREAD

**Issue by waltoss** [microsoft/genaiscript#934]
A follow-up on this discussion #926 

I suggest implementing a feature toggling mechanism per model to make it scale. For instance JSON Schema output is available on OpenAI, not on Anthropic, whereas Caching is on Anthropic and not on OpenAI. Same for seed, logit_bias, etc.

So it would looke more like

```typescript
export const MODEL_PROVIDERS: readonly {
    id: string
    detail: string
    url: string
    available_features: Feature[],
}

type Feature = "seed" | "logit_bias" | "ephemeral_caching" | "json_schema_output" | ...

...

isFeatureAvailable(model, "seed"): boolean
```

**Comment by pelikhan** [comment]
I've centralized the info in llms.json . Could you take a peek and review the anthropic feature set?

I will render this data in the docs too.

**Comment by pelikhan** [comment]
I'm going to mark this as closed. You will find then centralized model info at https://github.com/microsoft/genaiscript/blob/main/packages/core/src/llms.json . It is used to disable optional features like logprobs and also rendred in the docs.
