### ISSUE TITLE
VScode extension failing with an "unauthorized" message

### ISSUE THREAD

**Issue by msanvido** [microsoft/genaiscript#936]
Running a genaiscript (poem example) via the cli works fine, but running the same in VS code fails with a "Unauthorized message".
Looks like the installation fails with the following:
```
auth:undefined
hash:***
clients: connection unauthorized api-key=***, ***
url:/?api-key=***
api:**
```

<img width="488" alt="Image" src="https://github.com/user-attachments/assets/c8384feb-6b2b-4797-a35a-5782a15ba494" />

**Comment by pelikhan** [comment]
do you have 2 visual studio instance running by any chance?

**Comment by pelikhan** [comment]
Probable fix https://github.com/microsoft/genaiscript/pull/937

**Comment by pelikhan** [comment]
Dup of https://github.com/microsoft/genaiscript/issues/930

**Comment by pelikhan** [comment]
Please try again in v1.84.3

**Comment by pelikhan** [comment]
@msanvido the extension now opens a free port so you should not see this one again. Please reopen if it happens again.

**Comment by msanvido** [comment]
Wow! Thank you for the quick turnaround!!! I tested it and v.1.84.3 fixed the issue.
