### ISSUE TITLE
Bedrock support

### ISSUE THREAD

**Issue by volkanunsal** [microsoft/genaiscript#943]
Are there any plans to add support for  OpenAI API compatible models, such as Antopic models, hosted on AWS Bedrock?

**Comment by volkanunsal** [comment]
Specifically interested in using models hosted on Bedrock.

**Comment by volkanunsal** [comment]
What's the best way to test it? I created a genaiscript file like this:

```js
script({
    model: "anthropic_bedrock:anthropic.claude-3-haiku-20240307-v1:0",
})
$`Write a short poem.`

```

This is what I'm getting:

```
LLM error (403): LLM configuration missing for model anthropic_bedrock:anthropic.claude-3-haiku-20240307-v1:0
```

**Comment by volkanunsal** [comment]
I think `npx` might be using the global package...

**Comment by pelikhan** [comment]
Not released yet :)

**Comment by pelikhan** [comment]
Try


    yarn genai poem --model anthropic_bedrock:...


(fix model name)

**Comment by volkanunsal** [comment]
Nice! That worked.

**Comment by pelikhan** [comment]
I see, we generate system, user messages which become user, user in anthropic. need to collapse them.

**Comment by pelikhan** [comment]
@volkanunsal try the latest in the main branch

**Comment by volkanunsal** [comment]
Lgtm! Thanks for the quick turnaround.

**Comment by pelikhan** [comment]
Feel free to raise more issues as they pop up. Mostly relying on the @anthropic/bedrock-sdk package here

**Comment by volkanunsal** [comment]
Thank you. One potential area of improvement is allowing builders to
specify a designated credential profile to be used. This way they can use
the default credential profile for their dev work and run the genai scripts
to check their code etc without having to go back and forth between
accounts. I haven’t checked if that exists already…

**Comment by pelikhan** [comment]
One thing to try out would be to use the aws SDK in the genai script itself to set things up; then the environment would be ready when the LLM call happens.


Sent from Outlook<http://aka.ms/weboutlook>

________________________________

**Comment by volkanunsal** [comment]
I think I see what you mean. Anthropic SDK is using env vars to get the
credential values. Perhaps I can modify them beforehand.

**Comment by pelikhan** [comment]
open to suggestions once you get further in the usage :)

**Comment by volkanunsal** [comment]
This worked for me.  

```
process.env["AWS_ACCESS_KEY_ID"] = "..."
process.env["AWS_SECRET_ACCESS_KEY"] = "..."
process.env["AWS_SESSION_TOKEN"] = "..."

$`Write a short poem.`
```

To tidy it up, I put the creds in a separate file...

```
import "./creds"
$`Write a short poem.`
```

I was also able to make it work by exporting the credentials from `.env.genaiscript`. I think that's good enough for now. :)
