### ISSUE TITLE
Unable to Configure Model in Notebook

### ISSUE THREAD

**Issue by yaonan** [microsoft/genaiscript#956]
**Version**: `1.86.0`

**Description**

When trying to configure a model in a Notebook through the `script({ model: 'some-model' })` in JS script cell or the page config YAML, the model configuration does not take effect. 

The Notebook still prompts that no model has been selected or defaults to the model configured in the `.env` file.

During debugging, I found that in the `src/docsnotebook.ts` file, the `activateNotebookExecutor` function correctly parses the model from the meta (`const meta = parsePromptScriptMeta(jsSource)`), but it seems that the `meta.model` is not properly used as a parameter in the subsequent `startAIRequest` function in `src/state.ts`.

To temporary resolve this, I manually modified the compiled JS file in the VS Code extension directory as follows:

```js
        const { runId, request } = await client.startScript(
            template.id,
            files,
            {
                jsSource: options.jsSource,
                signal,
                trace,
                infoCb,
                partialCb,
                label,
                cache: cache ? template.cache : undefined,
                vars: structuredClone(options.parameters),
                model: template.model
            }
        )
```

After passing `model: template.model` in the third parameter, it seems to work as expected.

**Comment by yaonan** [comment]
At the same time, I found that when I try to use system prompts in the Notebook, it seems that they cannot be used either.

Currently, I can modify the src/docsnotebook.ts file mentioned above to add:

```
model: template.model,
system: template.system,
```

Additionally, the runScriptInternal function in `src/run.ts` needs to be modified as follows:

```ts
    const prj = await buildProject({
        toolFiles,
    })
    if (jsSource)
        prj.scripts.push({
            id: scriptId,
            jsSource,
        })
    const script = prj.scripts.find(
        (t) =>
            t.id === scriptId ||
            (t.filename &&
                GENAI_ANY_REGEX.test(scriptId) &&
                resolve(t.filename) === resolve(scriptId))
    )
    if (!script) throw new Error(`script ${scriptId} not found`)
    const fragment: Fragment = {
        files: Array.from(resolvedFiles),
    }
```

In the following section, add model and system:

```ts
        prj.scripts.push({
            id: scriptId,
            jsSource,
            model: options.model,
            system: options.system,
        })
        
```

In the original code, the script for the current Notebook Cell was added to `prj.scripts`, but it only included `template.id` and `jsSource`. I don’t know if this was by design or a bug. In any case, from this point on, the `script` no longer contains information such as model and system, and they are no longer included when called later.

**Comment by pelikhan** [comment]
Thanks for digging.
