### ISSUE TITLE
Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired in 1.86.2

### ISSUE THREAD

**Issue by pl-shernandez** [microsoft/genaiscript#960]
# Issue
We've been using genaiscript samples from the documentation for git commit message and pull request descriptor from our `package.json` inside a node project. 

In `@latest` / `@1.86.2` today we started receiving this error 

```
genaiscript: error
  trace: /Users/shernandez/GitHub/obfuscate-exciting-repo/PlaywrightTests/.genaiscript/runs/prd/2024-12-19T14-43-39-978Z.trace.md
LLM error (401): Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired.
```

# Troubleshooting
## Fix
Reverting to the last version resolves the issue
    "gcm": "npx genaiscript@1.85.1 run gcm",
    "prd": "npx genaiscript@1.85.1 run prd",
## Environment Variable Experiment
I looked at the documentation and tried adding that token scope environment variable corresponding to our endpoint `AZURE_OPENAI_TOKEN_SCOPES=https://southcentralus.api.cognitive.microsoft.com/.default` but that did not resolve it
https://microsoft.github.io/genaiscript/getting-started/configuration/#custom-token-scopes
I noticed navigating to that default without the `.default` https://cognitiveservices.azure.com/ is a site that can't be found

**Comment by pelikhan** [comment]
I did a change to clear the azure token; that may be it. I will send you a build to try out.

**Comment by pl-shernandez** [comment]
Gave that a try with my 1+1 = 2 script `npx genaiscript@1.86.3 run add` with and without the model set in the `script(`
```json wrap
{ "statusCode": 401, "message": "Unauthorized. Access token is missing, invalid, audience is incorrect (https://cognitiveservices.azure.com), or have expired." }
```

This is my current `.env` structure
```
AZURE_OPENAI_API_KEY=
AZURE_OPENAI_API_ENDPOINT=https://southcentralus.api.cognitive.microsoft.com/
GENAISCRIPT_DEFAULT_MODEL="azure:gpt-4o"
GENAISCRIPT_DEFAULT_SMALL_MODEL="azure:gpt-4o-mini"
GENAISCRIPT_DEFAULT_VISION_MODEL="azure:gpt-4o"
```

**Comment by pelikhan** [comment]
I am able to repro...

**Comment by pelikhan** [comment]
Try v1.84.4 . Turns out our proxy was behaving diferently from the raw AOAI layer. Test added.

**Comment by pl-shernandez** [comment]
Fixed thanks so much!
